import React from 'react'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const layout = () => {
  return (
    <div>layout</div>
  )
}

export default layout
