// import type { Metadata } from 'next'

// These styles apply to every route in the application
import "./../styles/global.css";

// export const metadata: Metadata = {
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
